import { createReducer } from "@reduxjs/toolkit";

const initialState = {
  questions: [
    {
      question: "What is the primary function of a biosensor?",
      choices: [
        "Measure blood pressure",
        "Detect and measure biological markers",
        "Generate medical images",
        "Monitor brain activity",
      ],
    },
    {
      question:
        "Which imaging modality uses magnetic fields and radio waves to create detailed images of the body's internal structures?",
      choices: ["X-ray", "CT scan", "MRI", "Ultrasound"],
    },
    {
      question: "What does ECG stand for in biomedical instrumentation?",
      choices: [
        "Electrocardiogram",
        "Electronic Control Generator",
        "Endoscopic Clinical Guidance",
        "External Cardiac Graph",
      ],
    },
    {
      question: "Tissue engineering is primarily focused on:",
      choices: [
        "Developing new medications",
        "Creating artificial intelligence systems",
        "Growing functional, artificial tissues",
        "Designing advanced imaging devices",
      ],
    },
    {
      question:
        "In rehabilitation engineering, what is a common application of assistive devices?",
      choices: [
        "Monitoring brain activity",
        "Growing artificial tissues",
        "Helping individuals with disabilities lead more independent lives",
        "Creating biosensors for medical diagnostics",
      ],
    },
    {
      question:
        "Which field of biomedical engineering involves the study of the mechanical aspects of living organisms?",
      choices: [
        "Biomedical Ethics",
        "Biomechanics",
        "Regulatory Affairs",
        "Medical Robotics",
      ],
    },
    {
      question: "What is a major consideration in biomedical ethics?",
      choices: [
        "Patient monitoring",
        "Informed consent",
        "Magnetic resonance imaging",
        "Tissue engineering",
      ],
    },
    {
      question:
        "What is a common application of medical robotics in healthcare?",
      choices: [
        "Monitoring patient vital signs",
        "Growing artificial organs",
        "Assisting in surgical procedures",
        "Designing biosensors",
      ],
    },
    {
      question:
        "What does the term 'biological signal processing' refer to in biomedical engineering?",
      choices: [
        "Analyzing and interpreting signals generated by the human body",
        "Growing artificial tissues",
        "Designing medical imaging devices",
        "Studying the ethics of biotechnology",
      ],
    },
    {
      question:
        "What is the purpose of regulatory affairs in biomedical engineering?",
      choices: [
        "Developing new medical devices",
        "Ensuring compliance with laws and regulations",
        "Growing artificial organs",
        "Studying the mechanical aspects of living organisms",
      ],
    },
  ],
  currentQuestion: 1,
  answers: [],
  markingScheme: [],
};

export const QuestionReducer = createReducer(initialState, {
  setCurrentQuestion: (state, action) => {
    state.currentQuestion = action.payload;
  },
  
  initializedAnswerSheet: (state) => {
    let answersArr = state.questions.map((q) => {
      return null;
    });
    return {
      ...state,
      answers: answersArr,
    };
  },

  answerQuestion: (state, action) => {
    let { qn, choice } = action.payload;

    let newAnswers = [...state.answers];
    newAnswers[qn] = choice;
    return {
      ...state,
      answers: newAnswers,
    };
  },

  initializedMakingScheme: (state, action) => {
    state.markingScheme = action.payload;
  },

});
